# Routes Admin avec prÃ©fixe /api
api_admin_controllers:
    resource:
        path: ../src/Controller/Admin/
        namespace: App\Controller\Admin
    type: attribute
    prefix: /api

# Routes des autres contrÃ´leurs (hors Admin)
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    exclude: '../src/Controller/Admin/'

# Import correct du dossier routes
app_routes:
    resource: 'routes/*.yaml'

# ðŸ‘‡ C'EST ICI QU'ON AJOUTE LA ROUTE DE CONNEXION ðŸ‘‡
api_login_check:
    path: /login_check